USE CPS;

CREATE TABLE REGION(
ID_REGION INT NOT NULL PRIMARY KEY,
NOMBRE_REGION VARCHAR(20)
);


CREATE TABLE TIPO_CLIENTE(
ID_TIPO_CLIENTE INT NOT NULL PRIMARY KEY,
CODIGO INT NOT NULL
);


CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(10) NOT NULL,
CORREO VARCHAR(50) NOT NULL,

);



CREATE TABLE PEDIDO(
ID_PEDIDO INT NOT NULL PRIMARY KEY,
ID_CLIENTE INT NOT NULL,
ID_TIPO_CLIENTE INT NOT NULL,
ID_PAQUETE INT NOT NULL,
ID_REGION INT NOT NULL,
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT FK_TIPO_CLIENTE FOREIGN KEY (ID_TIPO_CLIENTE) REFERENCES TIPO_CLIENTE(ID_TIPO_CLIENTE),
CONSTRAINT FK_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION),

);

CREATE TABLE FACTURA(
ID_FACTURA INT NOT NULL PRIMARY KEY,
ID_PEDIDO INT NOT NULL,
TOTAL_PAGAR DECIMAL(5,2),
CONSTRAINT FK_FACTURA FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);